### ISSUE TITLE
MVP: Reservations

### ISSUE THREAD

**Issue by briemcnally** [briemcnally/Open_Seated#3]
- [x] Logged in users can create reservations
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job on the seeding, it gives the whole site a new feeling.
Overall functionality is there, we just need to address a couple of details before we can consider this feature as an MVP.

- [x] On the home page, let's initialize the date as the day's current date.
- [x] Padding between the date and the party number.
     ![screen shot 2018-04-11 at 10 37 51 am](https://user-images.githubusercontent.com/1103663/38633422-70f3ded0-3d74-11e8-9d3a-c2247cfb4fc5.png)
- [x] If logged out, we are still allowed to make reservations, which breaks the site, let's tackle this.
      ![screen shot 2018-04-11 at 10 40 49 am](https://user-images.githubusercontent.com/1103663/38633525-d340490c-3d74-11e8-8ec5-bc5851328af5.png)
- [x] We should minimal validations, for example, you should not be able to create a reservation in the past.
- [x] Let's add some spacing on the last form before the actual reservation, it feels a little bit cluttered.
   ![screen shot 2018-04-11 at 10 44 08 am](https://user-images.githubusercontent.com/1103663/38633728-6313fa9c-3d75-11e8-8668-7bb2546e6211.png)

Feel free to mark the checkboxes yourself after addressing them. Assign this issue back to me once the updates are live in Heroku.

**Comment by AAlfarho** [comment]
- [x] Regarding validations for reservations in the past, we can still manually set dates in the past and successfully create a reservation. We need to validate this in the backend.
    + ![screen shot 2018-04-11 at 3 44 13 pm](https://user-images.githubusercontent.com/1103663/38647064-41a2f7e4-3d9f-11e8-8700-40325fab254f.png)
- [ ] (Optional) As a bonus, when trying to make a reservation `/#/restaurants/1/reservation/new` you are redirected to the _Login_ screen, after logging in, ideally we should redirect back to `/#/restaurants/1/reservation/new`.

 Assign this issue back to me once the validation is pushed to Heroku.

**Comment by AAlfarho** [comment]
Great job!
This completes our MVP feature for reservations, kudos!!

**Comment by AAlfarho** [comment]
Reopening this issue with a couple details.
- [ ] We need to clear the `Date cannot be in the past!` so it doesn't show up in new reservations.
- [ ] We cannot make reservations for the current day.
- [ ] Trying to make a reservation with proper info is hitting a `this.props.errors.map is not a function` error.
